/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    VButton: typeof import('./components/common/buttons/VButton.vue')['default']
    VButtonTool: typeof import('./components/common/buttons/VButtonTool.vue')['default']
    VCard: typeof import('./components/common/VCard.vue')['default']
    VDropdown: typeof import('floating-vue')['Dropdown']
    VIconButton: typeof import('./components/common/buttons/VIconButton.vue')['default']
    VInput: typeof import('./components/common/inputs/VInput.vue')['default']
  }
}
